namespace WinUI3Cpp
{
    [bindable]
    [default_interface]
    runtimeclass ViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {                       //^ For UWP with WinUI2, use Windows.UI.Xaml.Data.INotifyPropertyChanged
        ViewModel();
        
        //Simulates properties or "states" of the "view" that should be inside a "view-model"
        String thing{ get; };

        //The methods that this view-model supports
        Windows.Foundation.IAsyncAction StartProcess();
    }
}
