import "ViewModel.idl";
namespace WinUI2Cpp
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        ViewModel MainViewModel{ get; }; //usually a view-model is all you need for the idl file of your view
    }
}
