namespace WinUI2Cpp.ViewModels
{
    [bindable]
    [default_interface]
    runtimeclass Main : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {                       //^ For UWP with WinUI3, use Microsoft.UI.Xaml.Data.INotifyPropertyChanged
        Main();
        
        //Simulates properties or "states" of the "view" that should be inside a "view-model"
        String thing{ get; };

        //The methods that this view-model supports
        Windows.Foundation.IAsyncAction StartProcess();
    }
}
